SET SCHEMA APP;
CREATE TABLE COMPETITIONS (
		competID 		int NOT NULL PRIMARY KEY,
		competCountry	VARCHAR(32) NOT NULL,
		competName 		VARCHAR(32) NOT NULL,
		competYear 		VARCHAR(4) NOT NULL
	);

CREATE TABLE MATCHES (
		gameID			int NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
		team1			VARCHAR(32) NOT NULL,
		team2			VARCHAR(32) NOT NULL,
		matchDate		timestamp NOT NULL, 
		competID		int NOT NULL REFERENCES COMPETITIONS(competID)
	);
	
CREATE TABLE STATISTICS (
		statID			int NOT NULL PRIMARY KEY,
		team			VARCHAR(32) NOT NULL,
		gameID			int NOT NULL REFERENCES MATCHES(gameID)
	);
	
CREATE TABLE COMPOSITIONS (
		compoID			int NOT NULL PRIMARY KEY,
		team			VARCHAR(32) NOT NULL,
		player1			VARCHAR(32) NOT NULL,
		player2			VARCHAR(32) NOT NULL,
		player3			VARCHAR(32) NOT NULL,
		player4			VARCHAR(32) NOT NULL,
		player5			VARCHAR(32) NOT NULL,
		player6			VARCHAR(32) NOT NULL,
		player7			VARCHAR(32) NOT NULL,
		player8			VARCHAR(32) NOT NULL,
		player9			VARCHAR(32) NOT NULL,
		player10		VARCHAR(32) NOT NULL,
		player11		VARCHAR(32) NOT NULL,
		gameID			int NOT NULL REFERENCES MATCHES(gameID)
	);

CREATE TABLE GAMEEVENTS (
		gameEventID		int NOT NULL PRIMARY KEY,
		team			VARCHAR(32) NOT NULL,
		event			VARCHAR(30) NOT NULL,
		minuteOfEvent	int NOT NULL, 
		playerConcerned	VARCHAR(32) NOT NULL,
		playerEntering	VARCHAR(32) NOT NULL,
		gameID			int NOT NULL REFERENCES MATCHES(gameID)
	);
		
		
